//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18010
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linphone.BackEnd.OutOfProcess {
    
    
    internal sealed class RegistrationHelper {
        
        internal static string[] OutOfProcServerClassNames = new string[] {
                "Linphone.BackEnd.OutOfProcess.Server"};
    }
}
