//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linphone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linphone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linphone #version# SIP (rfc 3261) compatible phone under GNU Public License V2
        ///http://www.linphone.org
        ///
        ///Instructions
        ///http://www.linphone.org/m/help
        ///
        ///©2013 Belledonne Communications.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP account.
        /// </summary>
        public static string AccountMenu {
            get {
                return ResourceManager.GetString("AccountMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number or address.
        /// </summary>
        public static string AddressHint {
            get {
                return ResourceManager.GetString("AddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        public static string AdvancedSettingsMenu {
            get {
                return ResourceManager.GetString("AdvancedSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMR-NB.
        /// </summary>
        public static string AMRNBCodec {
            get {
                return ResourceManager.GetString("AMRNBCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMR-WB.
        /// </summary>
        public static string AMRWBCodec {
            get {
                return ResourceManager.GetString("AMRWBCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linphone.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string CallMenu {
            get {
                return ResourceManager.GetString("CallMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codecs.
        /// </summary>
        public static string CodecsMenu {
            get {
                return ResourceManager.GetString("CodecsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactMenu {
            get {
                return ResourceManager.GetString("ContactMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ContactsMenu {
            get {
                return ResourceManager.GetString("ContactsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugSetting {
            get {
                return ResourceManager.GetString("DebugSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string DeleteAllMenu {
            get {
                return ResourceManager.GetString("DeleteAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selection.
        /// </summary>
        public static string DeleteSelectionMenu {
            get {
                return ResourceManager.GetString("DeleteSelectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialer.
        /// </summary>
        public static string DialerMenu {
            get {
                return ResourceManager.GetString("DialerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G722.
        /// </summary>
        public static string G722Codec {
            get {
                return ResourceManager.GetString("G722Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM.
        /// </summary>
        public static string GSMCodec {
            get {
                return ResourceManager.GetString("GSMCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hang up.
        /// </summary>
        public static string HangUp {
            get {
                return ResourceManager.GetString("HangUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryMenu {
            get {
                return ResourceManager.GetString("HistoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILBC.
        /// </summary>
        public static string ILBCCodec {
            get {
                return ResourceManager.GetString("ILBCCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockScreen settings.
        /// </summary>
        public static string LockScreenSettings {
            get {
                return ResourceManager.GetString("LockScreenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute.
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string NetworkMenu {
            get {
                return ResourceManager.GetString("NetworkMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCMA.
        /// </summary>
        public static string PCMACodec {
            get {
                return ResourceManager.GetString("PCMACodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCMU.
        /// </summary>
        public static string PCMUCodec {
            get {
                return ResourceManager.GetString("PCMUCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send DTMFs as RFC2833.
        /// </summary>
        public static string RFC2833Setting {
            get {
                return ResourceManager.GetString("RFC2833Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SILK 16.
        /// </summary>
        public static string SILK16Codec {
            get {
                return ResourceManager.GetString("SILK16Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string SIPDomain {
            get {
                return ResourceManager.GetString("SIPDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound proxy.
        /// </summary>
        public static string SIPOutboundProxy {
            get {
                return ResourceManager.GetString("SIPOutboundProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SIPPassword {
            get {
                return ResourceManager.GetString("SIPPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string SIPProxy {
            get {
                return ResourceManager.GetString("SIPProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SIPUsername {
            get {
                return ResourceManager.GetString("SIPUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speaker.
        /// </summary>
        public static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speex 16.
        /// </summary>
        public static string Speex16Codec {
            get {
                return ResourceManager.GetString("Speex16Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speex 8.
        /// </summary>
        public static string Speex8Codec {
            get {
                return ResourceManager.GetString("Speex8Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string TransportSetting {
            get {
                return ResourceManager.GetString("TransportSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP.
        /// </summary>
        public static string TransportTCP {
            get {
                return ResourceManager.GetString("TransportTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS.
        /// </summary>
        public static string TransportTLS {
            get {
                return ResourceManager.GetString("TransportTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP.
        /// </summary>
        public static string TransportUDP {
            get {
                return ResourceManager.GetString("TransportUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel.
        /// </summary>
        public static string TunnelMenu {
            get {
                return ResourceManager.GetString("TunnelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel mode.
        /// </summary>
        public static string TunnelMode {
            get {
                return ResourceManager.GetString("TunnelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3G only.
        /// </summary>
        public static string TunnelMode3GOnly {
            get {
                return ResourceManager.GetString("TunnelMode3GOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string TunnelModeAlways {
            get {
                return ResourceManager.GetString("TunnelModeAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string TunnelModeAuto {
            get {
                return ResourceManager.GetString("TunnelModeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string TunnelModeDisabled {
            get {
                return ResourceManager.GetString("TunnelModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel port.
        /// </summary>
        public static string TunnelPort {
            get {
                return ResourceManager.GetString("TunnelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel server.
        /// </summary>
        public static string TunnelServer {
            get {
                return ResourceManager.GetString("TunnelServer", resourceCulture);
            }
        }
    }
}
