//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linphone.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linphone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linphone #version# SIP (rfc 3261) compatible phone under GNU Public License V2
        ///http://www.linphone.org
        ///
        ///Instructions
        ///http://www.linphone.org/m/help
        ///
        ///©2013 Belledonne Communications.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SIP account.
        /// </summary>
        public static string AccountMenu {
            get {
                return ResourceManager.GetString("AccountMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number or address.
        /// </summary>
        public static string AddressHint {
            get {
                return ResourceManager.GetString("AddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced settings.
        /// </summary>
        public static string AdvancedSettingsMenu {
            get {
                return ResourceManager.GetString("AdvancedSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AMR-NB.
        /// </summary>
        public static string AMRNBCodec {
            get {
                return ResourceManager.GetString("AMRNBCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AMR-WB.
        /// </summary>
        public static string AMRWBCodec {
            get {
                return ResourceManager.GetString("AMRWBCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à answer with video.
        /// </summary>
        public static string AnswerVideo {
            get {
                return ResourceManager.GetString("AnswerVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linphone.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Audio settings.
        /// </summary>
        public static string AudioSettingsMenu {
            get {
                return ResourceManager.GetString("AudioSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Audio stats.
        /// </summary>
        public static string AudioStatsMenu {
            get {
                return ResourceManager.GetString("AudioStatsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatically accept.
        /// </summary>
        public static string AutomaticallyAcceptVideoSetting {
            get {
                return ResourceManager.GetString("AutomaticallyAcceptVideoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatically initiate.
        /// </summary>
        public static string AutomaticallyInitiateVideoSetting {
            get {
                return ResourceManager.GetString("AutomaticallyInitiateVideoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Call.
        /// </summary>
        public static string CallMenu {
            get {
                return ResourceManager.GetString("CallMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cancel upload.
        /// </summary>
        public static string CancelUpload {
            get {
                return ResourceManager.GetString("CancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chat.
        /// </summary>
        public static string ChatMenu {
            get {
                return ResourceManager.GetString("ChatMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t create chat room for this SIP address, please check it is valid..
        /// </summary>
        public static string ChatRoomCreationError {
            get {
                return ResourceManager.GetString("ChatRoomCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Codecs.
        /// </summary>
        public static string CodecsMenu {
            get {
                return ResourceManager.GetString("CodecsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Console.
        /// </summary>
        public static string ConsoleMenu {
            get {
                return ResourceManager.GetString("ConsoleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string ContactMenu {
            get {
                return ResourceManager.GetString("ContactMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string ContactsAll {
            get {
                return ResourceManager.GetString("ContactsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacts.
        /// </summary>
        public static string ContactsMenu {
            get {
                return ResourceManager.GetString("ContactsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recents.
        /// </summary>
        public static string ContactsRecents {
            get {
                return ResourceManager.GetString("ContactsRecents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        public static string ContextMenuCopy {
            get {
                return ResourceManager.GetString("ContextMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save in library.
        /// </summary>
        public static string ContextMenuSave {
            get {
                return ResourceManager.GetString("ContextMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conversations.
        /// </summary>
        public static string ConversationsMenu {
            get {
                return ResourceManager.GetString("ConversationsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a linphone.org account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debug.
        /// </summary>
        public static string DebugSetting {
            get {
                return ResourceManager.GetString("DebugSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete All.
        /// </summary>
        public static string DeleteAllMenu {
            get {
                return ResourceManager.GetString("DeleteAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete logs file.
        /// </summary>
        public static string DeleteLogs {
            get {
                return ResourceManager.GetString("DeleteLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Selection.
        /// </summary>
        public static string DeleteSelectionMenu {
            get {
                return ResourceManager.GetString("DeleteSelectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialer.
        /// </summary>
        public static string DialerMenu {
            get {
                return ResourceManager.GetString("DialerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dialing....
        /// </summary>
        public static string Dialing {
            get {
                return ResourceManager.GetString("Dialing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string DownloadImage {
            get {
                return ResourceManager.GetString("DownloadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echo detected: {0} ms.
        /// </summary>
        public static string ECCalibrationDone {
            get {
                return ResourceManager.GetString("ECCalibrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No echo detected.
        /// </summary>
        public static string ECCalibrationDoneNoEcho {
            get {
                return ResourceManager.GetString("ECCalibrationDoneNoEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calibration failed.
        /// </summary>
        public static string ECCalibrationFailed {
            get {
                return ResourceManager.GetString("ECCalibrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calibration in progress.
        /// </summary>
        public static string ECCalibrationInProgress {
            get {
                return ResourceManager.GetString("ECCalibrationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click button to calibrate.
        /// </summary>
        public static string ECCalibrationNotRun {
            get {
                return ResourceManager.GetString("ECCalibrationNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echo canceller calibration.
        /// </summary>
        public static string EchoCancellerCalibration {
            get {
                return ResourceManager.GetString("EchoCancellerCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à edit password.
        /// </summary>
        public static string EditPassword {
            get {
                return ResourceManager.GetString("EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username and/or Domain cannot be empty.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving picture.
        /// </summary>
        public static string FileSaving {
            get {
                return ResourceManager.GetString("FileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation failed.
        /// </summary>
        public static string FileSavingFailure {
            get {
                return ResourceManager.GetString("FileSavingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation successful.
        /// </summary>
        public static string FileSavingSuccess {
            get {
                return ResourceManager.GetString("FileSavingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ICE.
        /// </summary>
        public static string FirewallPolicyIce {
            get {
                return ResourceManager.GetString("FirewallPolicyIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NAT.
        /// </summary>
        public static string FirewallPolicyNat {
            get {
                return ResourceManager.GetString("FirewallPolicyNat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string FirewallPolicyNone {
            get {
                return ResourceManager.GetString("FirewallPolicyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Firewall policy.
        /// </summary>
        public static string FirewallPolicySetting {
            get {
                return ResourceManager.GetString("FirewallPolicySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à STUN.
        /// </summary>
        public static string FirewallPolicyStun {
            get {
                return ResourceManager.GetString("FirewallPolicyStun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à G722.
        /// </summary>
        public static string G722Codec {
            get {
                return ResourceManager.GetString("G722Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à G729.
        /// </summary>
        public static string G729Codec {
            get {
                return ResourceManager.GetString("G729Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GSM.
        /// </summary>
        public static string GSMCodec {
            get {
                return ResourceManager.GetString("GSMCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H.264.
        /// </summary>
        public static string H264Codec {
            get {
                return ResourceManager.GetString("H264Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hang up.
        /// </summary>
        public static string HangUp {
            get {
                return ResourceManager.GetString("HangUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string HistoryAll {
            get {
                return ResourceManager.GetString("HistoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incoming.
        /// </summary>
        public static string HistoryIncoming {
            get {
                return ResourceManager.GetString("HistoryIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History.
        /// </summary>
        public static string HistoryMenu {
            get {
                return ResourceManager.GetString("HistoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missed.
        /// </summary>
        public static string HistoryMissed {
            get {
                return ResourceManager.GetString("HistoryMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outgoing.
        /// </summary>
        public static string HistoryOutgoing {
            get {
                return ResourceManager.GetString("HistoryOutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ILBC.
        /// </summary>
        public static string ILBCCodec {
            get {
                return ResourceManager.GetString("ILBCCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image received.
        /// </summary>
        public static string ImageMessageReceived {
            get {
                return ResourceManager.GetString("ImageMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INCOMING CALL.
        /// </summary>
        public static string IncomingCall {
            get {
                return ResourceManager.GetString("IncomingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The SIP address you provided is incorrect. Please ensure it matches the format username@domain..
        /// </summary>
        public static string InvalidSipAddressError {
            get {
                return ResourceManager.GetString("InvalidSipAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use linphone.org account.
        /// </summary>
        public static string LinphoneLogin {
            get {
                return ResourceManager.GetString("LinphoneLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LockScreen settings.
        /// </summary>
        public static string LockScreenSettings {
            get {
                return ResourceManager.GetString("LockScreenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loging in....
        /// </summary>
        public static string LoginIn {
            get {
                return ResourceManager.GetString("LoginIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection.
        /// </summary>
        public static string LoginMenu {
            get {
                return ResourceManager.GetString("LoginMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message received.
        /// </summary>
        public static string MessageReceived {
            get {
                return ResourceManager.GetString("MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mute.
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Network.
        /// </summary>
        public static string NetworkMenu {
            get {
                return ResourceManager.GetString("NetworkMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To:.
        /// </summary>
        public static string NewChatDest {
            get {
                return ResourceManager.GetString("NewChatDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        public static string NewChatMenu {
            get {
                return ResourceManager.GetString("NewChatMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PCMA.
        /// </summary>
        public static string PCMACodec {
            get {
                return ResourceManager.GetString("PCMACodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PCMU.
        /// </summary>
        public static string PCMUCodec {
            get {
                return ResourceManager.GetString("PCMUCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registered.
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed.
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In Progress.
        /// </summary>
        public static string RegistrationInProgress {
            get {
                return ResourceManager.GetString("RegistrationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report.
        /// </summary>
        public static string ReportCrash {
            get {
                return ResourceManager.GetString("ReportCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crash detected.
        /// </summary>
        public static string ReportCrashDialogCaption {
            get {
                return ResourceManager.GetString("ReportCrashDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application has detected a crash. 
        ///Do you want to report it to the developpers ? It will help fix it faster..
        /// </summary>
        public static string ReportCrashDialogMessage {
            get {
                return ResourceManager.GetString("ReportCrashDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scale down sent pictures.
        /// </summary>
        public static string ResizeSetting {
            get {
                return ResourceManager.GetString("ResizeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send DTMFs as RFC2833.
        /// </summary>
        public static string RFC2833Setting {
            get {
                return ResourceManager.GetString("RFC2833Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Self view enabled.
        /// </summary>
        public static string SelfViewEnabledSetting {
            get {
                return ResourceManager.GetString("SelfViewEnabledSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send by email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à send.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à send picture.
        /// </summary>
        public static string SendPicture {
            get {
                return ResourceManager.GetString("SendPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show.
        /// </summary>
        public static string ShowImage {
            get {
                return ResourceManager.GetString("ShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SILK 16.
        /// </summary>
        public static string SILK16Codec {
            get {
                return ResourceManager.GetString("SILK16Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domain.
        /// </summary>
        public static string SIPDomain {
            get {
                return ResourceManager.GetString("SIPDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send DTMFs as SIP INFO.
        /// </summary>
        public static string SIPInfoSetting {
            get {
                return ResourceManager.GetString("SIPInfoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outbound proxy.
        /// </summary>
        public static string SIPOutboundProxy {
            get {
                return ResourceManager.GetString("SIPOutboundProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string SIPPassword {
            get {
                return ResourceManager.GetString("SIPPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy.
        /// </summary>
        public static string SIPProxy {
            get {
                return ResourceManager.GetString("SIPProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auth userid.
        /// </summary>
        public static string SIPUserId {
            get {
                return ResourceManager.GetString("SIPUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string SIPUsername {
            get {
                return ResourceManager.GetString("SIPUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à speaker.
        /// </summary>
        public static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speex 16.
        /// </summary>
        public static string Speex16Codec {
            get {
                return ResourceManager.GetString("Speex16Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speex 8.
        /// </summary>
        public static string Speex8Codec {
            get {
                return ResourceManager.GetString("Speex8Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string StatDownloadBW {
            get {
                return ResourceManager.GetString("StatDownloadBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Codec.
        /// </summary>
        public static string StatPayload {
            get {
                return ResourceManager.GetString("StatPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à stats.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload.
        /// </summary>
        public static string StatUploadBW {
            get {
                return ResourceManager.GetString("StatUploadBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stun server.
        /// </summary>
        public static string StunServer {
            get {
                return ResourceManager.GetString("StunServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To:.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transport.
        /// </summary>
        public static string TransportSetting {
            get {
                return ResourceManager.GetString("TransportSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TCP.
        /// </summary>
        public static string TransportTCP {
            get {
                return ResourceManager.GetString("TransportTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TLS.
        /// </summary>
        public static string TransportTLS {
            get {
                return ResourceManager.GetString("TransportTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UDP.
        /// </summary>
        public static string TransportUDP {
            get {
                return ResourceManager.GetString("TransportUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tunnel.
        /// </summary>
        public static string TunnelMenu {
            get {
                return ResourceManager.GetString("TunnelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tunnel mode.
        /// </summary>
        public static string TunnelMode {
            get {
                return ResourceManager.GetString("TunnelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3G only.
        /// </summary>
        public static string TunnelMode3GOnly {
            get {
                return ResourceManager.GetString("TunnelMode3GOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always.
        /// </summary>
        public static string TunnelModeAlways {
            get {
                return ResourceManager.GetString("TunnelModeAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto.
        /// </summary>
        public static string TunnelModeAuto {
            get {
                return ResourceManager.GetString("TunnelModeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string TunnelModeDisabled {
            get {
                return ResourceManager.GetString("TunnelModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tunnel port.
        /// </summary>
        public static string TunnelPort {
            get {
                return ResourceManager.GetString("TunnelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tunnel server.
        /// </summary>
        public static string TunnelServer {
            get {
                return ResourceManager.GetString("TunnelServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uploading....
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vibrate on incoming message.
        /// </summary>
        public static string VibratorSetting {
            get {
                return ResourceManager.GetString("VibratorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video activation.
        /// </summary>
        public static string VideoActivationPopupCaption {
            get {
                return ResourceManager.GetString("VideoActivationPopupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have been proposed video, would you like to accept it?.
        /// </summary>
        public static string VideoActivationPopupContent {
            get {
                return ResourceManager.GetString("VideoActivationPopupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video enabled.
        /// </summary>
        public static string VideoEnabledSetting {
            get {
                return ResourceManager.GetString("VideoEnabledSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video settings.
        /// </summary>
        public static string VideoSettingsMenu {
            get {
                return ResourceManager.GetString("VideoSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video stats.
        /// </summary>
        public static string VideoStatsMenu {
            get {
                return ResourceManager.GetString("VideoStatsMenu", resourceCulture);
            }
        }
    }
}
